"""Initial database schema: ContextGroup, Context, Message, File

Revision ID: 4804461b35ca
Revises: 
Create Date: 2025-06-08 14:29:53.414145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4804461b35ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_summary', sa.String(), nullable=True),
    sa.Column('file_content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('context_groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_contents', sa.String(), nullable=False),
    sa.Column('context_size', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('context_group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['context_group_id'], ['context_groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('contexts')
    op.drop_table('context_groups')
    op.drop_table('files')
    # ### end Alembic commands ###
